version: "3.8"

services:
  backend:
    build: .
    env_file: .env
    ports:
      - "8080:8080"

  chainlit:
    build:
      context: .
      dockerfile: Dockerfile.chainlit
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
